# Generated by Django 4.1.7 on 2023-04-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('NCC', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MKH', models.CharField(max_length=255, unique=True)),
                ('name_KH', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('name_hang', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('NCC', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
