# Generated by Django 4.1.7 on 2023-04-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
