# Generated by Django 4.2.1 on 2023-05-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='serial',
            field=models.IntegerField(max_length=50, unique=True),
        ),
    ]
