# Generated by Django 4.1.7 on 2023-04-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0002_delete_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('NCC', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='serial',
        ),
        migrations.AlterField(
            model_name='warranty',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
