# Generated by Django 4.1.7 on 2023-04-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0004_warranty_mkh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='end_date',
            field=models.DateField(),
        ),
    ]
