# Generated by Django 4.1.7 on 2023-04-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0007_alter_phone_serial_alter_warranty_mkh'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='expiration_date',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
