# Generated by Django 4.1.7 on 2023-04-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0008_phone_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='expiration_date',
        ),
    ]
